customers/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='homey')),
    path('customer/', include('customers.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='homey')),
    path('customer/', include('customers.urls')),
	path('accounts/login/', auth_views.LoginView.as_view(), name='login'),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *
from .views import (
    list_pesanan_admin, update_status_pesanan,
    list_pengaduan_admin, update_status_pengaduan,
)
from .views import ShippingView
from .views import list_pengaduan_user, tambah_pengaduan

app_name = 'homey'
urlpatterns = [
    path('', HomeView.as_view(template_name='home/indexhome.html', paginate_by=4), name='index'),
    path('products/', HomeView.as_view(template_name='home/producthome.html', paginate_by=6), name='product'),
    path('products/<slug:slug>/', ProductDetail.as_view(template_name='home/detail.html'), name='detail'),
    path('cart/', HomeView.as_view(template_name='home/cart.html'), name="cart"),
    path('checkout/', ShippingView, name='checkout'),
    path('payment-confirm/', payment_confirm, name='payment-confirm'),
    path('checkout/success/', TemplateView.as_view(template_name='home/checkout_success.html'), name='checkout-success'),
    path('payment-success/', payment_success, name='payment-success'),
    path('update-item/', updateItem, name='update-item'),
    path('admin/pesanan/', list_pesanan_admin, name='list_pesanan_admin'),
    path('admin/pesanan/update/<int:order_id>/', update_status_pesanan, name='update_status_pesanan'),
    path('pengaduan/', list_pengaduan_user, name='list_pengaduan_user'),
    path('pengaduan/tambah/', tambah_pengaduan, name='tambah_pengaduan'),  # 🧨 Tambahin ini!
    path('staff/pengaduan/', list_pengaduan_staff, name='pengaduan_staff'),
    path('staff/pengaduan/update/<int:pengaduan_id>/', update_status_pengaduan, name='update_status_pengaduan'),
]

home/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse
import random

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    logo_category = models.ImageField(null=True, blank=True, upload_to='logo/')
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            return self.logo_category.url
        except:
            return ''

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, unique=True)
    old_price = models.DecimalField(blank=True, null=True, max_digits=8, decimal_places=3)
    price = models.DecimalField(max_digits=8, decimal_places=3)
    description = models.TextField()
    upload_time = models.DateField(auto_now_add=True)
    stock = models.IntegerField(default=1)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    @property
    def imageThumbnail(self):
        image = ProductImage.objects.filter(product=self).first()
        return image.imageURL if image else '/static/empty.png'

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=False, upload_to='images/')

    def __str__(self):
        return self.product.name

    @property
    def imageURL(self):
        try:
            return self.image.url
        except:
            return '/static/empty.png'

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_order = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=255, null=True, unique=True)

    STATUS_CHOICES = [
        ('belum_dikirim', 'Belum Dikirim'),
        ('dikirim', 'Dikirim'),
        ('sampai', 'Sampai'),
    ]
    status_pengiriman = models.CharField(max_length=20, choices=STATUS_CHOICES, default='belum_dikirim')

    def __str__(self):
        return f"Order #{self.id}"

    def save(self, *args, **kwargs):
        if not self.transaction_id:
            self.transaction_id = random.randrange(100, 99999999)
        super().save(*args, **kwargs)

    @property
    def get_cart_totals(self):
        return sum(item.get_total for item in self.orderitem_set.all())

    @property
    def get_cart_items(self):
        return sum(item.quantity for item in self.orderitem_set.all())

class OrderItem(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL, blank=True)
    order = models.ForeignKey(Order, null=True, on_delete=models.SET_NULL, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product.name)

    @property
    def get_total(self):
        return self.product.price * self.quantity

class ShippingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='shipping_user')
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    email = models.EmailField(default="test@example.com")
    kota = models.CharField(max_length=100)
    address = models.TextField(default='address not filled in')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

    def get_absolute_url(self):
        return reverse('homey:index')

class Pengaduan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)
    judul = models.CharField(max_length=100)
    isi = models.TextField()
    tanggal = models.DateTimeField(auto_now_add=True)

    STATUS_PENGADUAN = [
        ('pending', 'Menunggu'),
        ('processing', 'Diproses'),
        ('resolved', 'Selesai'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_PENGADUAN, default='pending')

    def __str__(self):
        return f"{self.judul} - {self.status}"

home/forms.py
from django import forms
from .models import Order, Pengaduan

class FormShipping(forms.Form):
    email = forms.EmailField()
    kota = forms.CharField(max_length=100)
    address = forms.CharField(widget=forms.Textarea)

class UpdateOrderStatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status_pengiriman']

class UpdatePengaduanStatusForm(forms.ModelForm):
    class Meta:
        model = Pengaduan
        fields = ['status']

home/views.py
from django.shortcuts import render, redirect
from .forms import FormShipping
from home import models
from .models import *
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
import json
import requests
from .utils import *
from django.views.generic import (
    TemplateView,
    DetailView,
    ListView,
)
from django.contrib.admin.views.decorators import staff_member_required
from .forms import UpdateOrderStatusForm, UpdatePengaduanStatusForm
from .models import Order, Pengaduan
from .models import Pengaduan
from .decorators import staff_pengaduan_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required



class HomeView(ListView):
    models = Product
    category = Category.objects.all()
    queryset = models.objects.all()
    extra_context = {
        'categories' : category
    }
    
    def get_queryset(self):
        request = self.request.GET
        if len(request) != 0:
            if next(iter(request)) == 'category':
                self.queryset = Product.objects.filter(category_id=self.request.GET['category'])

        return super().get_queryset()

    def get_ordering(self):
        request = self.request.GET
        if len(request) != 0:
            for i in request: 
                if i == 'more-filter':
                    ordering = [request["more-filter"]]
                    return ordering

    def get_context_data(self,*args,**kwargs):
        # fakeStoreAPI()
        request = self.request
        context = super().get_context_data()
        # print("bum",context,"bum") 
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        for product in context["product_list"]:
            product_images = ProductImage.objects.filter(product=product.pk)
            print(product_images)
        if len(request.GET) != 0:
            if next(iter(request.GET)) == 'category-id':
                context['active'] = Category.objects.get(id=request.GET['category-id'])
        context.update(cartData(self.request))
        if context['items'] != "0":
            context.update(mergeFunction(request,context['items']))
        return context

class ProductDetail(TemplateView):
    model = Product
    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        context['product'] = self.model.objects.get(slug=kwargs['slug'])

        product_images = ProductImage.objects.filter(product=context['product'].pk)
        for image in product_images:
            print(image.imageURL)

        context["prod_images"] = product_images
        exclude_object = Product.objects.exclude(slug=kwargs['slug'])
        paginator = Paginator(exclude_object,4)
        prod_list = paginator.get_page(None)
        context['product_list']=prod_list
        return context

@login_required
def ShippingView(request):
    context = {}
    form = FormShipping
    cart = cartData
    context.update(cart(request))
    if request.method == 'POST':
        form = FormShipping(request.POST)
        if form.is_valid():
            customer = request.user
            shipping,created = ShippingAddress.objects.get_or_create(
                user=customer,
                order=context['order'],
                email=request.POST.get('email'),
                kota=request.POST.get('kota'),
                address=request.POST.get('address'),
            )         
            shipping.save()
            CompleteOrder(request)
            return redirect('homey:checkout-success')
    context['form']=form
    return render(request, 'home/checkout.html', context)
print(">>> MASUK KE SHIPPING VIEW <<<")

from django.contrib import messages

@login_required
def payment_confirm(request):
    if request.method == 'POST':
        # bisa update order jadi "Menunggu Konfirmasi" kalau mau
        messages.success(request, 'Pembayaran dikonfirmasi! Order kamu akan segera diproses.')
        return redirect('homey:index')
    
def payment_success(request):
    return render(request, 'home/checkout_success.html')
  


def fakeStoreAPI():
    # This function will store data from api to django.
    responses=requests.get('https://fakestoreapi.com/products?limit=5').json()

    for response in responses:
        category = Category.objects
        obj = Product.objects.create(
            category=Category.objects.get(name=response['category']),
            name=response['title'],
            img_product1=response['image'],
            price=response['price'],
            description=response['description']
        )
        obj.save()
        # try:
        #     cat,created = Category.objects.get_or_create(name=response['category'])

        #     print('mantap gann!')
        # except:
        #     print('error gan')
    print('sipp')


@login_required
def updateItem(request):
    data = json.loads(request.body)
    print(request.body)
    productId = data['productId']
    action = data['action']
    print(productId,action,'hai')
    customer = request.user
    product = Product.objects.get(id=productId)
    order,created = Order.objects.get_or_create(user=customer, complete=False)
    orderItem,created = OrderItem.objects.get_or_create(order=order, product=product)
    if action =='add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item Was Added', safe=False)

@staff_member_required
def list_pesanan_admin(request):
    orders = Order.objects.all()
    return render(request, 'admin/orders.html', {'orders': orders})

@staff_member_required
def update_status_pesanan(request, order_id):
    order = Order.objects.get(id=order_id)
    form = UpdateOrderStatusForm(request.POST or None, instance=order)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('list_pesanan_admin')
    return render(request, 'admin/update_order.html', {'form': form})

@staff_member_required
def list_pengaduan_admin(request):
    laporan = Pengaduan.objects.all()
    return render(request, 'admin/pengaduan.html', {'laporan': laporan})

@staff_member_required
def update_status_pengaduan(request, laporan_id):
    laporan = Pengaduan.objects.get(id=laporan_id)
    form = UpdatePengaduanStatusForm(request.POST or None, instance=laporan)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('list_pengaduan_admin')
    return render(request, 'admin/update_pengaduan.html', {'form': form})

@login_required
def list_pengaduan_user(request):
    laporan = Pengaduan.objects.filter(user=request.user)
    return render(request, 'home/pengaduan_user.html', {'laporan': laporan})

@login_required
def tambah_pengaduan(request):
    if request.method == 'POST':
        judul = request.POST.get('judul')
        isi = request.POST.get('isi')
        order_id = request.POST.get('order_id')

        Pengaduan.objects.create(
            user=request.user,
            order_id=order_id,
            judul=judul,
            isi=isi,
        )
        return redirect('list_pengaduan_user')
    
    orders = Order.objects.filter(user=request.user)
    return render(request, 'home/form_pengaduan.html', {'orders': orders})

@login_required
@staff_pengaduan_required
def list_pengaduan_staff(request):
    pengaduan = Pengaduan.objects.all().order_by('-tanggal')
    return render(request, 'home/pengaduan_list_staff.html', {'pengaduan': pengaduan})

@login_required
@staff_pengaduan_required
def update_status_pengaduan(request, pengaduan_id):
    pengaduan = get_object_or_404(Pengaduan, id=pengaduan_id)
    if request.method == "POST":
        new_status = request.POST.get("status")
        if new_status in dict(Pengaduan.STATUS_PENGADUAN).keys():
            pengaduan.status = new_status
            pengaduan.save()
        return redirect('homey:pengaduan_staff')
    return render(request, 'home/update_pengaduan.html', {'pengaduan': pengaduan})

templates/home/checkout_success.html
{% extends 'base.html' %}
<h2>Thank You {{ name }}!</h2>
<p>Your order is being processed..</p>
<a href="/">Back to Homepage</a>

{% block content %}
<div class="container mt-5">
  <div class="text-center p-5 bg-white shadow rounded">
    <h2 class="mb-4 text-success">🎉 Pembayaran Diterima!</h2>
    <p>Thank you, Your order is being processed.</p>
    <p>We will contact you via email or WhatsApp for delivery confirmation..</p>
    <a href="{% url 'homey:product' %}" class="btn btn-primary mt-3">Kembali Belanja</a>
  </div>
</div>
{% endblock content %}

templates/home/indexhome.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'style2.css' %}">
	
{% endblock style %}
{% block content %}
	    <!-- Jumbotron Start -->

        <div class="under-nav">
            <div class="jumbotron jumbotron-edit">
                <div class="flex-items flex-1">
                    <p class="jumbotron-text">
                        Hot Product<br>Buy Now
                    </p>
                    <a class="btn btn-light btn-jumbo" href="{% url 'homey:product' %}" role="button">Check Now</a>
                </div>
            </div>
        </div>

        <!-- Jumbotron End -->

        
        <!-- Category Section Start -->
        
        <div class="section-content h-275">
            <div class="container-content">
                <div class="d-flex flex-column w-100 top-section">
					<div class="d-flex justify-content-between align-items-center w-100 font-rubik-bold">
						<p class="link-href section-title purple-shadow">Categories</p>
					</div>
				</div>
                <div class="d-flex flex-container mb-4 mt-3">
                    {% for category in categories %}
                        <div class="flex-items-2">
                            <a href="{% url 'homey:product' %}?category={{category.id}}"><div class="circle circle-satu" style="background-image:url({{category.imageURL}})"></div></a>
                            <p class="text-center font-rubik-bold purple-shadow">{{category.name}}</p>
                        </div>
                    {% endfor %}
	            </div>
            </div>
        </div>
    
        <!-- Category Section End -->


        <!-- Product List Start -->

        <div class="section-content">
            <div class="container-content">
                <div class="d-flex flex-column w-100 top-section">
                    <div class="d-flex justify-content-between align-items-center w-100 font-rubik-bold">
                        <p class="link-href section-title purple-shadow">Best Products</p>
                        <a href="#" class="text-decoration-none">   
                            <span>See All.</span>
                        </a>
                    </div>
                    <div class="row justify-content-center mt-3">
						{% for product in product_list %}
							<div class="col-md-3 col-sm-6 kartu-produk">
								<figure class="card card-product-grid mb-3">
									<div class="img-wrap img-product"> <a href="{% url 'homey:detail' product.slug %}"><img src="{{product.imageThumbnail}}" class='img-product d-flex mx-auto'> </a></div>
									<figcaption class="info-wrap text-center">
										<a href="{% url 'homey:detail' product.slug %}" class="title-product text-decoration-none text-truncate">{{product.name}}</a>
										<p class="price-product price mb-2">Rp {{product.price}} </p>
										<a href="" data-action='add' data-product='{{product.id}}' class="btn btn-primary btn-lg update-cart"> Add to cart </a>
									</figcaption>
								</figure>
							</div> <!-- col.// -->
						{% endfor %}
					</div> <!-- row .//  -->
                </div>
            </div>
        </div>

        <!-- Product List End -->

{% endblock content %}

templates/home/pengaduan_list_staff.html
{% extends "home/base.html" %}
{% block content %}
<h2>Daftar Pengaduan Masuk</h2>
<table>
    <tr>
        <th>Judul</th>
        <th>User</th>
        <th>Tanggal</th>
        <th>Status</th>
        <th>Aksi</th>
    </tr>
    {% for p in pengaduan %}
    <tr>
        <td>{{ p.judul }}</td>
        <td>{{ p.user.username }}</td>
        <td>{{ p.tanggal }}</td>
        <td>{{ p.get_status_display }}</td>
        <td><a href="{% url 'homey:update_status_pengaduan' p.id %}">Update</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/home/pengaduan_user.html
{% extends 'base.html' %}
{% block content %}
<h2>Daftar Pengaduan Kamu</h2>
<ul>
    {% for aduan in laporan %}
        <li>
            <strong>{{ aduan.judul }}</strong> - {{ aduan.status }} <br>
            {{ aduan.isi }} <br>
            <small>{{ aduan.tanggal }}</small>
        </li>
    {% empty %}
        <li>Belum ada pengaduan</li>
    {% endfor %}
</ul>
<a href="{% url 'homey:tambah_pengaduan' %}">Tambah Pengaduan</a>
{% endblock %}

templates/home/producthome.html
{% extends "base.html" %}
{% block style %}
<style>
	.title-product{
		font-size:1.1rem;
        font-weight: 700;
		color: black;
        font-family: 'Roboto', sans-serif;
	}

	.price-product{
		font-size: 1rem;
        font-weight: 600;

	}
</style>
{% endblock style %}
{% block content %}
    <!-- ========================= SECTION PAGETOP ========================= -->
    <section class="section-pagetop bg under-nav ">
        <div class="container">
            <h2 class="title-page">Category products</h2>
            <nav>
            <ol class="breadcrumb text-white">
                <li class="breadcrumb-item" aria-current="page"><a href="{% url 'homey:index' %}">Home</a></li>
                {% if active %}
                <li class="breadcrumb-item" aria-current="page"><a href="{% url 'homey:product' %}">Products</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{active}}</li>
                {% else %}
                <li class="breadcrumb-item active" aria-current="page">Products</li>
                {% endif %}
            </ol>  
            </nav>
        </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->
    

    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
    <div class="container">

    <div class="row">
        <aside class="col-md-3 mt-4">
            <form method="GET">
                <div class="card">
                    <article class="filter-group">
                        <div class="card-header d-flex flex-column">
                            <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="false" class="">
                                <i class="icon-control fa fa-chevron-down"></i>
                                <h6 class="title">Category Products</h6>
                            </a>
                        </div>
                        <div class="filter-content collapse in" id="collapse_1" style="">
                            <div class="card-body">
                                {% for category in categories %}
                                    <label class="custom-control custom-checkbox">
                                        <input type="radio" name="category" value="{{category.id}}" class="custom-control-input">
                                        <div class="custom-control-label">{{category}}</div>
                                    </label>
                                {% endfor %} 
                            </div> <!-- card-body.// -->
                        </div>
                    </article> <!-- filter-group  .// -->
                </div> <!-- card.// -->

                <div class="card">
                    <article class="filter-group">
                        <div class="card-header d-flex flex-column">
                            <a href="#" data-toggle="collapse" data-target="#collapse_2" aria-expanded="false" class="">
                                <i class="icon-control fa fa-chevron-down"></i>
                                <h6 class="title">More Filter</h6>
                            </a>
                        </div>
                        <div class="filter-content collapse in" id="collapse_2" style="">
                            <div class="card-body">
                                <label class="custom-control custom-checkbox">
                                    <input type="radio" name="more-filter" value="-upload_time" class="custom-control-input">
                                    <div class="custom-control-label">Terbaru</div>
                                </label>
                                <label class="custom-control custom-checkbox">
                                    <input type="radio" name="more-filter" value="-price" class="custom-control-input">
                                    <div class="custom-control-label">Termahal</div>
                                </label>
                                <label class="custom-control custom-checkbox">
                                    <input type="radio" name="more-filter" value="price" class="custom-control-input">
                                    <div class="custom-control-label">Termurah</div>
                                </ul>
                            </div> <!-- card-body.// -->
                        </div>
                    </article> <!-- filter-group  .// -->
                </div> <!-- card.// -->
                <button type="submit" class="btn btn-primary mt-4">Filter</button>
            </form>
        </aside> <!-- col.// -->
    <main class="col-md-9 mt-4">

    <div class="row">
        <!--<div class="col-md-4">
            <figure class="card card-product-grid">
                <div class="img-wrap"> 
                    <span class="badge badge-danger"> NEW </span>
                    <img src="images/items/1.jpg">
                    <a class="btn-overlay" href="#"><i class="fa fa-search-plus"></i> Quick view</a>
                </div>
                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="#" class="title">Great item name goes here</a>
                        <div class="price-wrap mt-2">
                            <span class="price">$1280</span>
                            <del class="price-old">$1980</del>
                        </div>
                    </div>
                    <a href="#" class="btn btn-block btn-primary">Add to cart </a>
                </figcaption>
            </figure>
        </div> --><!-- col.// -->
        
        
            
        {% for product in product_list %}
            <div class="col-md-4 col-sm-6 col-6 p-1">
                <figure class="card card-product-grid" style="height: 400px;">
                    <div class="img-wrap img-product"> 
                        <a href="{% url 'homey:detail' product.slug %}"><img src="{{product.imageThumbnail}}"></a>
                        <a class="btn-overlay" href="{% url 'homey:detail' product.slug %}"><i class="fa fa-search-plus"></i> Quick view</a>
                    </div> <!-- img-wrap.// -->
                    <figcaption class="info-wrap text-center ">
                        <div class="fix-height">
                            <a href="{% url 'homey:detail' product.slug %}" class="title title-product text-decoration-none">{{product.name}}</a>
                            <div class="price-wrap mt-2">
                                <span class="price price-product">Rp {{product.price}}</span>
                            </div> <!-- price-wrap.// -->
                        </div>
                        {% if is_user %}
                        <!-- Jika user adalah anonymous maka -->
                            <button type="button" class="btn btn-block btn-primary mt-2" data-toggle="modal" data-target="#exampleModal">
                                Add To Cart
                            </button>
                        {% else %}
                        <!-- Lain Jika user sudah log in -->
                            <a data-action='add' data-product='{{product.id}}' href="" class="btn btn-block btn-primary update-cart mt-2">Add to cart </a>  
                        {% endif %}
                    </figcaption>
                </figure>
            </div> <!-- col.// -->
        {% endfor %}
    </div> <!-- row end.// -->
    <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Log In Dibutuhkan</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Agar Bisa Memasukkan Item Keranjang Anda Harus Login
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a href="{% url 'login' %}" class="btn btn-primary">Log In</a>
            </div>
            </div>
        </div>
        </div>
    
    {% if path %} <!-- Jika Ada Filter Maka... -->
        <nav class="mt-4" aria-label="Page navigation sample">
        {% if is_paginated %}
        <ul class="pagination">
            
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="{{path}}&page={{page_obj.previous_page_number}}">Previous</a></li>    
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}    
        {% for i in paginator.page_range %}
            <li class="page-item"><a class="page-link" href="{{path}}&page={{i}}">{{i}}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="{{path}}&page={{page_obj.next_page_number}}">Next</a></li>    
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        {% endif %} 
        </ul>
        {% endif %}
        </nav>
    {% else %}<!-- LAIN Jika Tidak Ada Filter Maka... -->
    <nav class="mt-4" aria-label="Page navigation sample">
        {% if is_paginated %}
        <ul class="pagination">
            
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="{% url 'homey:product' %}?page={{page_obj.previous_page_number}}">Previous</a></li>    
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}    
        {% for i in paginator.page_range %}
            <li class="page-item"><a class="page-link" href="{% url 'homey:product' %}?page={{i}}">{{i}}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="{% url 'homey:product' %}?page={{page_obj.next_page_number}}">Next</a></li>    
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        {% endif %} 
        </ul>
        {% endif %}
        </nav>
    {% endif %}
        
    </main> <!-- col.// -->

    </div>

    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

{% block script %}
    
{% endblock script %}
    
    